### PR TITLE
Updated sdk-list.md

### PR DESCRIPTION
**Pull request by GiancarloLelli**
Hi,
I've recently published a library that wraps the REST API endpoints and provides an easy an intuitive Sdk to work with. Hope this helps somehow.

### CODE REVIEW

**Comment by sakley** [comment]
### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C2%5C13%5C8c57cf75-5f19-a48b-d5fc-fd709203ffd6%5CPullRequest%5C201702131326509504-18%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by bfreydier** [comment]
Hello,

Thanks a lot for your interest in Groove API.
We've forwarded your request for approval to our legal teams and will come back to you as soon as possible.

Thanks

**Comment by GiancarloLelli** [comment]
Awesome, thanks.
Feel free to send me an email if needed.

**Comment by GiancarloLelli** [comment]
Hello @bfreydier 
Any news on this PR?

Thanks
Giancarlo

**Comment by sakley** [comment]
Hi Giancarlo, 
Unfortunately, for legal reasons, we cannot add this link to our SDK page.
I'm very sorry- you can reference it though as a comment on our docs website for example.
Thanks a lot,

**Pull request closed without merging**
